
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import Navbar from "../components/layout/Navbar";
import ThemeRegistry from "../components/ThemeRegistry";
import { LocalizationProvider } from '@mui/x-date-pickers/LocalizationProvider';
import { AdapterDayjs } from '@mui/x-date-pickers/AdapterDayjs';

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Mi App Web",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={roboto.className}>
      <body>
        <LocalizationProvider dateAdapter={AdapterDayjs}>
          <ThemeRegistry>
            <Navbar />
            {children}
          </ThemeRegistry>
        </LocalizationProvider>
      </body>
    </html>
  );
}
