# version: '3.8'

services:
  backend:
    build: ./backend
    container_name: tesis-backend-simple
    restart: unless-stopped
    command: sh -c "pnpm prisma migrate deploy && pnpm run start:prod"
    ports:
      - "1708:80"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${PORT}
      - CORS_ORIGIN=${CORS_ORIGIN}
    networks:
      - tesis-red

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_CLIENTVAR: ${NEXT_PUBLIC_API_URL}
    container_name: tesis-frontend-simple
    restart: unless-stopped
    ports:
      - "1709:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_CLIENTVAR=${NEXT_PUBLIC_API_URL}
    depends_on:
      - backend
    networks:
      - tesis-red

networks:
  tesis-red:
    driver: bridge

